### ISSUE TITLE
Projektbeschreibung

### ISSUE THREAD

**Issue by PascalRoider** [PascalRoider/Web_Technologie_Projekt#1]
[Projekt_WebTech.pdf](https://github.com/user-attachments/files/17093236/Projekt_WebTech.pdf)

**Comment by oliver-jung** [comment]
Das passt wunderbar und bietet ausreichend Flexibilität in der Umsetzung.

Wichtig ist, dass es zumindest an einer Stelle ein wenig Datenverarbeitung und interaktive Elemente gibt. Das Kader bietet sich hierfür an - z.B. Informationen in maschinenlesbarer Form > Dynamische Visualisierung auf "virtuellem Spielfeld" > Detailinformationen bei Klick auf den Spieler. Zu Umsetzungmöglichkeiten hierzu mehr bei den Einheiten zur clientseitigen Programmierung

Außerdem sollte man sich überlegen wie die Tabelle aktualisiert wird (manuell durch dich - sehr einfach, mittels API sofern verfügbar - mittelmäßig oder mittels Web Scraper von einer externen Seite - mittelmäßig bis komplex)
